config/routes.rb
Rails.application.routes.draw do
  resources :scrapers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  ################## Validations ##################
  validates :job_title, presence: true, length: { maximum: 255 }
  validates :company, presence: true, length: { maximum: 255 }
  validates :location, length: { maximum: 255 }
  validates :country, length: { maximum: 255 }
  validates :apply_link, length: { maximum: 255 }
  # validates_uniqueness_of :apply_link
end

app/models/scraper.rb
class Scraper < ApplicationRecord
  has_many :scraper_logs

end

app/models/scraper_log.rb
class ScraperLog < ApplicationRecord
  belongs_to :scraper

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/scrapers_controller.rb
class ScrapersController < ApplicationController
  before_action :set_scraper, only: [:show, :edit, :update, :destroy]

  # GET /scrapers
  # GET /scrapers.json
  def index
    @scrapers = Scraper.all
  end

  # GET /scrapers/1
  # GET /scrapers/1.json
  def show
  end

  # GET /scrapers/new
  def new
    @scraper = Scraper.new
  end

  # GET /scrapers/1/edit
  def edit
  end

  # POST /scrapers
  # POST /scrapers.json
  def create
    @scraper = Scraper.new(scraper_params)

    respond_to do |format|
      if @scraper.save
        format.html { redirect_to @scraper, notice: 'Scraper was successfully created.' }
        format.json { render :show, status: :created, location: @scraper }
      else
        format.html { render :new }
        format.json { render json: @scraper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scrapers/1
  # PATCH/PUT /scrapers/1.json
  def update
    respond_to do |format|
      if @scraper.update(scraper_params)
        format.html { redirect_to @scraper, notice: 'Scraper was successfully updated.' }
        format.json { render :show, status: :ok, location: @scraper }
      else
        format.html { render :edit }
        format.json { render json: @scraper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scrapers/1
  # DELETE /scrapers/1.json
  def destroy
    @scraper.destroy
    respond_to do |format|
      format.html { redirect_to scrapers_url, notice: 'Scraper was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scraper
      @scraper = Scraper.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scraper_params
      params.require(:scraper).permit(:thread_size, :proxy_usage, :http_method)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scrapers_helper.rb
module ScrapersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SGejob</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <nav class="navbar navbar-light">
      <h2 class="brand"><%= image_tag 'job-icon.png' %> SogeJob</h2>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/scrapers/_form.html.erb
<%= form_with(model: scraper, local: true) do |form| %>
  <% if scraper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(scraper.errors.count, "error") %> prohibited this scraper from being saved:</h2>

      <ul>
      <% scraper.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :thread_size %>
    <%= form.number_field :thread_size %>
  </div>

  <div class="field">
    <%= form.label :proxy_usage %>
    <%= form.check_box :proxy_usage %>
  </div>

  <div class="field">
    <%= form.label :http_method %>
    <%= form.text_field :http_method %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/scrapers/edit.html.erb
<h1>Editing Scraper</h1>

<%= render 'form', scraper: @scraper %>

<%= link_to 'Show', @scraper %> |
<%= link_to 'Back', scrapers_path %>

app/views/scrapers/index.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-responsive">
  <thead>
    <tr>
      <th>Tried count</th>
      <th>Saved Job count</th>
      <th>India</th>
      <th>Germany</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= ScraperLog.sum(:records_found) %></td>
      <td><%= Job.count %></td>
      <td><%= Job.where(country: 'India').count %></td>
      <td><%= Job.where(country: 'Germany').count %></td>


    </tr>
  </tbody>
</table>
<h3>Scrapers</h3>
<table class="table table-responsive">
  <thead>
    <tr>
      <th>Name</th>
      <th>Thread size</th>
      <th>Proxy usage</th>
      <th>Http method</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @scrapers.each do |scraper| %>
      <tr>
        <td><%= scraper.name %></td>
        <td><%= scraper.thread_size %></td>
        <td><%= scraper.proxy_usage %></td>
        <td><%= scraper.http_method %></td>
        <td>
          <%= link_to 'Run', '', class: 'btn btn-xs btn-success' %>
          <%= link_to 'Edit', edit_scraper_path(scraper), class: 'btn btn-xs btn-secondary' %>
          <%= link_to 'Destroy', scraper, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/scrapers/new.html.erb
<h1>New Scraper</h1>

<%= render 'form', scraper: @scraper %>

<%= link_to 'Back', scrapers_path %>

app/views/scrapers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Thread size:</strong>
  <%= @scraper.thread_size %>
</p>

<p>
  <strong>Proxy usage:</strong>
  <%= @scraper.proxy_usage %>
</p>

<p>
  <strong>Http method:</strong>
  <%= @scraper.http_method %>
</p>

<%= link_to 'Edit', edit_scraper_path(@scraper) %> |
<%= link_to 'Back', scrapers_path %>